import { DocumentAnalysisProvider, AnalysisOptions, AnalysisResult } from '../types';
import { ChecklistItemStatus, ChecklistItemCategory } from '../../../../types';

/**
 * MockOCRProvider
 * 
 * Developer reference for implementing a new OCR/Analysis provider.
 * Demonstrates how to swap Gemini for Amazon Textract, Azure Form Recognizer, 
 * or a local Tesseract implementation.
 */
export class MockOCRProvider implements DocumentAnalysisProvider {
    name = 'MockProvider';

    async analyze(fileBase64: string, mimeType: string, options: AnalysisOptions): Promise<AnalysisResult> {
        console.log(`[MockOCRProvider] Simulating analysis for ${mimeType} from ${options.fromCountry} to ${options.toCountry}...`);

        // Artificial delay
        await new Promise(resolve => setTimeout(resolve, 800));

        return {
            extractedData: {
                sellerName: "Mock Exporter Corp",
                buyerName: "Mock Importer Ltd",
                originCountry: options.fromCountry,
                destinationCountry: options.toCountry,
                products: [
                    {
                        name: "Simulated Cargo",
                        quantity: "1000 units",
                        hsCode: "000000",
                        isOrganic: false,
                        attributes: ["Fresh"]
                    }
                ],
                securityAnalysis: {
                    isSuspicious: false,
                    tamperScore: 0,
                    suspicionReason: "Verified by Mock Engine"
                }
            },
            checklist: [
                {
                    id: `mock-${Date.now()}`,
                    documentName: "Simulated Health Certificate",
                    description: "Requirement generated by Mock Provider",
                    issuingAgency: "Mock Authority",
                    agencyLink: "https://example.gov",
                    category: ChecklistItemCategory.REGULATORY,
                    isMandatory: true,
                    status: ChecklistItemStatus.MISSING
                }
            ]
        };
    }
}
